### ISSUE TITLE
No-std support

### ISSUE THREAD

**Issue by kellda** [danielhenrymantilla/byte-strings-rs#6]
It would be nice to be able to use this crate in no-std environments. Is there any reason against it ?

`core::ffi::CStr` (as opposed to `std::ffi::CStr`) requires Rust 1.64. The MSRV could be bumped, or a feature can be added to switch between `core::ffi::CStr` and `std::ffi::CStr`.

Which implementation would you accept ?

**Comment by kellda** [comment]
BTW `std::CStr::from_bytes_with_nul_unchecked` is const since Rust 1.59. I guess it would be nice to use that instead of the current `byte_strings::const_::CStr`. Would it be OK to bump the MSRV of the `const-friendly` feature from 1.56 to 1.59 ?

**Comment by danielhenrymantilla** [comment]
Yeah, `1.59.0` is more than one year old, so we can definitely target that as a new MSRV. Do you want to take a stab at the PR?
