### ISSUE TITLE
Upgrade to syn 2.0

### ISSUE THREAD

**Issue by glts** [danielhenrymantilla/byte-strings-rs#7]
Syn 2.0 was recently released. An upgrade to syn 2.0 in byte-strings would be welcome.

I tried building byte-strings with syn 2.0, and it seems to work without changes. However, the MSRV will need to be raised to 1.56.

Thank you.

**Comment by glts** [comment]
Revisiting this just now … I use `c_str!` quite a bit in my crates. Now with my other dependencies at syn 2, I’d like to avoid also pulling in and compiling syn 1.

I wonder if you have plans to make an upgrade to syn 2.0? Or would you like me to open a pull request with the syn and MSRV bump?

**Comment by danielhenrymantilla** [comment]
Thanks for the reminder, I've decided to go with a big semver bump (and thus `0.3.0` release), since it was time for some updates!

  - #8
